services:
  boilerplate.publicapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=@Sdf123!@#
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/boilerplate.pfx
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https:ro
    depends_on:
      - boilerplate.database